pipeline {
    agent any

    stages {
        stage('Build Frontend') {
            steps {
                script {
                    sh 'docker build -t papapandajr/frontend:latest ./app/frontend'
                }
            }
        }

        stage('Build Backend') {
            steps {
                script {
                    sh 'docker build -t papapandajr/backend:latest ./app/backend'
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                script {
                    sh 'kubectl apply -f k8s/'
                }
            }
        }
    }
}ls -al ~/.ssh